config/routes.rb
Rails.application.routes.draw do
  root 'ripples#index'
  
  get '/ripples/oldest', 'ripples#oldest'
  get '/ripples/next', 'ripples#next'
  get '/ripples/previous', 'ripples#previous'
  resources :ripples, :except => [:edit, :destroy]


  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  
end

app/models/ripple.rb
class Ripple < ActiveRecord::Base
  default_scope -> {order(created_at: :desc)}
  validates :name, :message, presence: true
  validates :url, allow_blank: true, format: {
    with: URI::regexp(%w(http https)), 
         message: "Must be a url starting with http:// or https://"
  }
   
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/ripples_controller.rb
class RipplesController < ApplicationController
  before_action :set_ripple, only: [:show, :update]
  before_action :restrict_destroy_edit, only: [:edit, :destroy]
  
  RIPPLES_PER_PAGE = 10

  # GET /ripples
  # GET /ripples.json
  def index
    session[:page] = 0
    @ripples = Ripple.limit(RIPPLES_PER_PAGE).offset(session[:page] * RIPPLES_PER_PAGE)
  end

  # GET /ripples/1
  # GET /ripples/1.json
  def show
  end

  # GET /ripples/new
  def new
    @ripple = Ripple.new
  end

  
  def next
    size = Ripple.all.size
    pages = size / 10
    if (session[:page] > (pages - 1)) 
      @ripples = Ripple.limit(RIPPLES_PER_PAGE).offset(session[:page] * RIPPLES_PER_PAGE)      
    else
      session[:page] += 1
      @ripples = Ripple.limit(RIPPLES_PER_PAGE).offset(session[:page] * RIPPLES_PER_PAGE)
    end
    
    render :index
  end
  
  def previous
    if (session[:page] == 0) 
      @ripples = Ripple.limit(RIPPLES_PER_PAGE).offset(session[:page] * RIPPLES_PER_PAGE)      
    else
      session[:page] -= 1
      @ripples = Ripple.limit(RIPPLES_PER_PAGE).offset(session[:page] * RIPPLES_PER_PAGE)
    end
    
    render :index
  end
  
  def oldest
    size = Ripple.all.size
    pages = size / 10  
    session[:page] = pages
    @ripples = Ripple.limit(RIPPLES_PER_PAGE).offset(session[:page] * RIPPLES_PER_PAGE)  
    render :index
  end

  # POST /ripples
  # POST /ripples.json
  def create
    @ripple = Ripple.new(ripple_params)

    respond_to do |format|
      if @ripple.save
        format.html { redirect_to root_url}
        format.json { render :show, status: :created, location: @ripple }
      else
        format.html { render :new }
        format.json { render json: @ripple.errors, status: :unprocessable_entity }
      end

    end

  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ripple
      @ripple = Ripple.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ripple_params
      params.require(:ripple).permit(:name, :url, :message)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ripples_helper.rb
module RipplesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CONSCIOUS/Mess</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class='<%= controller.controller_name %>'>
  	<div id="banner">
  	  <h1>CONSCIOUS/Mess</h1>
  	  <h2>...a stream of anonymous online ramblings</h2>	
  	</div>
    <%= yield %>
  </body>
</html>

app/views/ripples/_form.html.erb
<%= form_for(ripple) do |f| %>
  <% if ripple.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ripple.errors.count, "error") %> prohibited this ripple from being saved:</h2>

      <ul>
      <% ripple.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= "Your name or alias (required)" %><br>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= "A website, yours or otherwise (optional)" %><br>
    <%= f.text_field :url %>
  </div>

  <div class="field">
    <%= "Your message/note/quote/rant (required)" %><br>
    <%= f.text_area :message, rows: 10, cols: 60 %>
  </div>

  <div class="actions">
    <%= f.submit %>

  </div>
<% end %>

app/views/ripples/index.html.erb
<p id="notice"><%= notice %></p>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Message</th>
      <th>Time Stamp</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ripples.each do |ripple| %>
      <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">
        <td>
        	<% if ripple.url.to_s.empty? %>
        	  <%= ripple.name %>
        	<% else %>
        	  <a href= <%= ripple.url %>><%= ripple.name %></a>
        	<% end %>
        </td>
        <td><%= truncate(ripple.message, length: 50) %></td>
	    <td><%= ripple.created_at %></td>
        <td><%= link_to 'Show', ripple %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<div id = "nav">
	<button><%= link_to 'Newest', ripples_path %></button>
	<button><%= link_to 'Previous 10 Ripples', ripples_previous_path %></button>
	<button><%= link_to 'Next 10 Ripples', ripples_next_path %></button>
	<button><%= link_to 'Oldest', ripples_oldest_path %></button>
    <button><%= link_to 'New Ripple', new_ripple_path %></button>
</div>

app/views/ripples/new.html.erb
<h1>Say What's On Your Mind</h1>

<%= render 'form', ripple: @ripple %>

<%= link_to 'Back', ripples_path %>

app/views/ripples/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong><%= @ripple.name %> said:</strong>
</p>

<p class = 'message_alter'>
  <%= @ripple.message %>
</p>

<%= link_to 'Back', ripples_path %>